version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "registerToken"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10asu3rd3oaxk"
s3_prefix = "registerToken"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
